// Code generated by assets/generate.go. DO NOT EDIT.

package flag

import "github.com/ebiiim/fantasy/base"

func initData() {
	m[base.ObjUndef] = None
	m[base.ObjNone] = None
	m[base.ObjBG] = BlockAll
	m[base.ObjMeadow] = TerrainLand | TerrainSky
	m[base.ObjGrass] = None
	m[base.ObjTree] = BlockLand
	m[base.ObjBox] = ItemBox
	m[base.ObjWater] = TerrainSea | TerrainSky
	m[base.ObjMe] = Me
}
