// Code generated by assets/generate.go. DO NOT EDIT.

package flag

import "github.com/ebiiim/fantasy/base"

func initData() {
	m[base.ObjUndef] = BlockAll
	m[base.ObjNone] = None
	m[base.ObjBG] = BlockAll
	m[base.ObjBase] = None
	m[base.ObjGrass] = None
	m[base.ObjTree] = LandObject
	m[base.ObjBox] = Box
	m[base.ObjMe] = Me
}
