// Code generated by assets/generate.go. DO NOT EDIT.

package camera

import (
	"github.com/ebiiim/fantasy/base"
)

func initData() {
	m[base.ObjUndef] = loadImg("assets/img/undef.png")
	m[base.ObjNone] = loadImg("assets/img/none.png")
	m[base.ObjBG] = loadImg("assets/img/bg.png")
	m[base.ObjMeadow] = loadImg("assets/img/meadow.png")
	m[base.ObjGrass] = loadImg("assets/img/grass.png")
	m[base.ObjTree] = loadImg("assets/img/tree.png")
	m[base.ObjBox] = loadImg("assets/img/box.png")
	m[base.ObjWater] = loadImg("assets/img/water.png")
	m[base.ObjSheep] = loadImg("assets/img/sheep.png")
	m[base.ObjMonster] = loadImg("assets/img/monster.png")
	m[base.ObjMe] = loadImg("assets/img/me.png")
}
