// Code generated by assets/generate.go. DO NOT EDIT.

package base

func initData() {
	m[ObjUndef] = None
	m[ObjNone] = None
	m[ObjBG] = BlockAll
	m[ObjMeadow] = TerrainLand | TerrainSky
	m[ObjGrass] = None
	m[ObjTree] = BlockLand
	m[ObjBox] = ItemBox
	m[ObjWater] = TerrainSea | TerrainSky
	m[ObjMe] = Me
}
