// Code generated by assets/generate.go. DO NOT EDIT.

package base

const (
	ObjUndef Object = iota // 0
	ObjNone                // 1
	ObjBG                  // 2
	ObjBase                // 3
	ObjGrass               // 4
	ObjTree                // 5
	ObjBox                 // 6
	ObjWater               // 7
	ObjMe                  // 8
)
