// Code generated by assets/generate.go. DO NOT EDIT.

package base

const (
	ObjUndef   ObjectType = iota // 0
	ObjNone                      // 1
	ObjBG                        // 2
	ObjMeadow                    // 3
	ObjGrass                     // 4
	ObjTree                      // 5
	ObjBox                       // 6
	ObjWater                     // 7
	ObjSheep                     // 8
	ObjMonster                   // 9
	ObjMe                        // 10
)
