// Code generated by assets/generate.go. DO NOT EDIT.

package img

import (
	"github.com/ebiiim/fantasy/base"
)

func initData() {
	m[base.ObjUndef] = load("assets/undef.png")
	m[base.ObjNone] = load("assets/none.png")
	m[base.ObjBG] = load("assets/bg.png")
	m[base.ObjBase] = load("assets/base.png")
	m[base.ObjGrass] = load("assets/grass.png")
	m[base.ObjTree] = load("assets/tree.png")
	m[base.ObjBox] = load("assets/box.png")
	m[base.ObjMe] = load("assets/me.png")
}
